### ISSUE TITLE
Help with computing the AUPR values

### ISSUE THREAD

**Issue by RuneBlaze** [Roy-lab/merlin-p_inferred_networks#1]
Hi. I am using this dataset as part of a class project, and at least two other classmates and I had difficulty computing the AUPR values. We tried scikit-learn's [PR curve](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_recall_curve.html), calculating it manually according to the original MERLIN+p paper, and also (done by me) tried using the [AUCCalculator java package](http://mark.goadrich.com/programs/AUC/), as was mentioned in the original paper. I am going to describe what I did, and what I got (that differed from the values of the original paper).

I took the inferred network (`GENIE3.KO.txt` from the yeast dataset in this case, assuming everything decompressed) and one gold standard network. With each weighted edge of the inferred network, I checked if the edge of this inferred network is in the gold standard network or not (the `true_label`), and took the weight of this edge `w`. Then I outputted a line `w true_label` to the output (that will be consumed by AUCCalculator). I did this for every edge of the inferred network to output a list (say `output.txt`) to be consumed by AUCCalculator. Then I ran AUCCalculator with the list I just outputted (`java -jar auc.jar output.txt list`). [Here](https://gist.github.com/RuneBlaze/f68e965001d2e340fae6a618efb03084) is the Python3 script I used to produce this list (`output.txt`). This script can be run using the following command (when the current working directory is under `yeast_networks`):

```bash
python3 aupr.py -i inferred/GENIE3.KO.txt  -g gold/YEASTRACT_Count3.KO.txt
java -jar auc.jar output.txt list # assuming auc.jar is in the same directory for AUCCalculator
```

The output of `auc.jar` at the end is:

```
--- Writing PR file output.txt.pr ---
--- Writing standardized PR file output.txt.spr ---
--- Writing ROC file output.txt.roc ---
Area Under the Curve for Precision - Recall is 0.0016797763357218832
Area Under the Curve for ROC is 0.5409468267526518
```

which is off by somewhat a magnitude from the original reported value (0.018) of the paper. This also happens (values that are off by somewhat a magnitude) with other pairs of data (other inferred networks, other gold standard networks). It is very possible that we did not read carefully/just don't understand how to process the data, but we would appreciate any help in recovering the correct AUPR values.

**Comment by asiahpirani** [comment]
Hi,

There are a couple of issues.

First, to calculate the AUPR, we were removing (TF, Target) pairs in inferred network, where TF or Target is not in the gold standard. This is done to make the comparison more fair. If a TF or a Target is not in the gold standard, any inferred edge involving these genes will just add to false positives.

The second point is that, in your setup, you probably need to add the false negatives and true negatives to your list too.
Something like this:

```
tfs = set([])
tgs = set([])
for (a,b) in golden_edges:
	tfs.add(a)
	tgs.add(b)
y_true = []
probs_pred = []
for a in tfs:
	for b in tgs:
		if (a,b) in golden_edges:
			l = 1
		else:
			l = 0
		if (a,b) in inferred_edges:
			v = inferred_edges[(a,b)]
		else:
			v = 0
		probs_pred.append(v)
		y_true.append(l)
```
Using this, I get AUPR of 0.02151336200111959 which is still slightly off from the value reported in the paper.

I looked at my old files for the paper, and I realized I have two sets of AUPR values, they are the same for NatVar and Stress Response networks, but differ for KO networks (for example for GENIE3 on YEASTRACT_Count3 I have 0.018 and 0.0215).

Looking further, I realized I had two sets of inferred networks for KO datasets (if I remember correctly, one before collapsing replicates in the expression matrix, and one after).

I calculated the AUPR for both, and I get 0.021 for inferred network before collapsing replicates, and 0.018 for the network after collapsing replicates. So it looks like the AUPR for KO networks in the paper are correct, but I had uploaded the wrong (old) KO networks here.

I should be able to upload the correct KO networks to the repository in a few days.
Meanwhile, using the code suggested above should give you the same AUPR as in the paper for the NatVar and Stress Response networks.

Please let me know if you encounter any other issues.

Thanks,
Alireza

**Comment by RuneBlaze** [comment]
Hi,

Many thanks for the quick reply (and spending time to look at my code fixing it)! In hindsight, it was stupid of me to not considering removing the edges that are simply not in the gold standard, and now I think I understand how I should calculate the AUPR values.

Btw I don't think any of us actually need the "correct" KO network (we are not trying to replicate the paper. We were just very worried that our code calculated the AUPR incorrectly) for this course project, so it should be completely fine at least for us to just use the one currently uploaded.

Best,
Baqiao
